//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftExpressWinFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fature
    {
        public int Id { get; set; }
        public string Emertimi { get; set; }
        public string Njesia { get; set; }
        public Nullable<System.DateTime> DatasKdences { get; set; }
        public double Cmimi { get; set; }
        public string Lloji { get; set; }
        public bool KaTvsh { get; set; }
        public string Tipi { get; set; }
        public string Barkod { get; set; }
    }
}
